import { buildClientData, slugify, TEMPLATE_MAP, type TemplateKey } from "template-shared";
import type { LeadRecord } from "@/lib/types";

export type SiteCategory = TemplateKey; // "landing" | "booking" | "payments"

export const SITE_CATEGORIES: readonly SiteCategory[] = ["landing", "booking", "payments"];

/**
 * Maps a LeadRecord into the `RawLeadJson` shape template-shared's
 * buildClientData() expects (mirrors demo-generator's client.json
 * "business" sub-object).
 */
export function leadToRawJson(lead: LeadRecord, category: SiteCategory) {
  return {
    business: {
      name: lead.businessName,
      category: lead.niche || "Local Business",
      phone: lead.phoneNumber || "",
      email: lead.email || "",
      address: lead.address || lead.city || "",
      website: lead.websiteUrl || "",
      photo: "",
      rating: lead.googleRating ?? undefined,
      reviewCount: undefined,
      openingHours: [],
      googleMapsUrl: lead.googleMapsLink || "",
    },
    meta: { template: category },
  };
}

/** Pure: lead + category -> { repoName, templateRepo, shape, clientData }. */
export function buildSiteGenerationPlan(lead: LeadRecord, category: SiteCategory) {
  const shape = category === "landing" ? "landing" : "booking";
  const templateRepo = TEMPLATE_MAP[category];
  const repoName = slugify(lead.businessName);
  const clientData = buildClientData(leadToRawJson(lead, category), { shape });
  return { repoName, templateRepo, shape, clientData };
}

/**
 * Pure: produces the exact client.js file body for landing-shape repos,
 * matching template-landing-page's `window.CLIENT_DATA = {...}` format.
 */
export function buildClientJsContent(clientData: unknown): string {
  return `// Generated by Agency-CRM lead-to-site connector\n// ${new Date().toISOString()}\nwindow.CLIENT_DATA = ${JSON.stringify(clientData, null, 2)};\n`;
}

const GITHUB_API = "https://api.github.com";
const GITHUB_ORG = "O-I-AI-soultions";

export class GitHubApiError extends Error {
  constructor(
    message: string,
    public status: number,
    /** True when the response carried GitHub's rate-limit-exhausted signal
     *  (429, or 403 with `X-RateLimit-Remaining: 0`) — lets callers
     *  distinguish rate-limiting from a generic 403 permission failure. */
    public rateLimited = false
  ) {
    super(message);
  }
}

/**
 * Thrown by `waitForRepoReady` when the polling timeout elapses without the
 * repo's template files (specifically client.json) becoming available.
 */
export class RepoNotReadyError extends Error {
  constructor(public repoFullName: string) {
    super(`Repo ${repoFullName} did not become ready before timeout`);
  }
}

async function githubRequest(path: string, init: RequestInit) {
  const token = process.env.GITHUB_API_TOKEN;
  if (!token) throw new GitHubApiError("Missing GITHUB_API_TOKEN", 500);

  const res = await fetch(`${GITHUB_API}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      ...(init.headers || {}),
    },
  });

  if (!res.ok) {
    const body = await res.json().catch(() => null);
    const rateLimited =
      res.status === 429 ||
      (res.status === 403 && res.headers.get("x-ratelimit-remaining") === "0");
    throw new GitHubApiError(
      body?.message || `GitHub API error (HTTP ${res.status})`,
      res.status,
      rateLimited
    );
  }
  return res.json();
}

/** Step 1: create repo from template. Returns the new repo's html_url + full_name. */
export async function createRepoFromTemplate(templateRepo: string, repoName: string) {
  return githubRequest(`/repos/${GITHUB_ORG}/${templateRepo}/generate`, {
    method: "POST",
    body: JSON.stringify({
      owner: GITHUB_ORG,
      name: repoName,
      private: true,
      include_all_branches: false,
    }),
  }) as Promise<{ html_url: string; full_name: string }>;
}

/**
 * Polls a newly-generated repo until its template files have actually
 * landed, using `GET /repos/{repoFullName}/contents/client.json` as the
 * readiness signal (see module docs above for the race this guards against).
 *
 * - 200 -> ready, resolves immediately (first check happens with no upfront
 *   sleep, so the already-ready case costs exactly one request).
 * - 404 (`GitHubApiError` with status 404) -> not ready yet, wait
 *   `intervalMs` and retry.
 * - Any other error propagates immediately (rate limit, 5xx, missing token,
 *   etc.) — it is not swallowed into the timeout.
 * - If `timeoutMs` elapses without a 200, rejects with `RepoNotReadyError`.
 */
export async function waitForRepoReady(
  repoFullName: string,
  options?: { timeoutMs?: number; intervalMs?: number }
): Promise<void> {
  const timeoutMs = options?.timeoutMs ?? 20000;
  const intervalMs = options?.intervalMs ?? 1500;
  const deadline = Date.now() + timeoutMs;

  while (true) {
    try {
      await githubRequest(`/repos/${repoFullName}/contents/client.json`, {
        method: "GET",
      });
      return;
    } catch (err) {
      if (!(err instanceof GitHubApiError) || err.status !== 404) throw err;
      // Not ready yet — fall through to the timeout/retry check below.
    }

    if (Date.now() >= deadline) {
      throw new RepoNotReadyError(repoFullName);
    }

    await new Promise((resolve) => setTimeout(resolve, intervalMs));
  }
}

/** Step 2: commit (create or update) a file's content via Contents API. */
export async function putRepoFile(
  repoFullName: string,
  filePath: string,
  content: string,
  message: string
) {
  // Must check for an existing file SHA first — PUT requires `sha` to
  // update an existing file, omitting it only works for file creation.
  // Template-generated repos already contain client.json/client.js with
  // placeholder content, so this is always an update, not a create.
  let sha: string | undefined;
  try {
    const existing = (await githubRequest(`/repos/${repoFullName}/contents/${filePath}`, {
      method: "GET",
    })) as { sha: string };
    sha = existing.sha;
  } catch (err) {
    if (!(err instanceof GitHubApiError) || err.status !== 404) throw err;
    // 404 is fine — file doesn't exist yet, sha stays undefined (create).
  }

  return githubRequest(`/repos/${repoFullName}/contents/${filePath}`, {
    method: "PUT",
    body: JSON.stringify({
      message,
      content: Buffer.from(content, "utf8").toString("base64"),
      ...(sha ? { sha } : {}),
    }),
  });
}

const VERCEL_API = "https://api.vercel.com";
const VERCEL_TEAM_ID = "team_iTMkW2op53QZywks7RYsa63k";

export class VercelApiError extends Error {
  constructor(message: string, public status: number) {
    super(message);
  }
}

/** Thrown by `waitForDeploymentReady` when the polling timeout elapses
 *  without the deployment reaching `READY`. */
export class DeploymentNotReadyError extends Error {
  constructor(public deploymentId: string, public lastState?: string) {
    super(`Deployment ${deploymentId} did not become ready before timeout (last state: ${lastState ?? "unknown"})`);
  }
}

async function vercelRequest(path: string, init: RequestInit) {
  const token = process.env.VERCEL_API_TOKEN;
  if (!token) throw new VercelApiError("Missing VERCEL_API_TOKEN", 500);

  const url = `${VERCEL_API}${path}${path.includes("?") ? "&" : "?"}teamId=${VERCEL_TEAM_ID}`;
  const res = await fetch(url, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      ...(init.headers || {}),
    },
  });

  if (!res.ok) {
    const body = await res.json().catch(() => null);
    throw new VercelApiError(
      body?.error?.message || `Vercel API error (HTTP ${res.status})`,
      res.status
    );
  }
  return res.json();
}

/** Step 3: create a Vercel project linked to the given GitHub repo. */
export async function createVercelProject(repoName: string) {
  return vercelRequest(`/v11/projects`, {
    method: "POST",
    body: JSON.stringify({
      name: repoName,
      gitRepository: { type: "github", repo: `${GITHUB_ORG}/${repoName}` },
    }),
  }) as Promise<{ id: string; name: string }>;
}

/** Step 4: explicitly trigger a production deployment from the repo's default branch. */
export async function triggerDeployment(repoName: string) {
  return vercelRequest(`/v13/deployments`, {
    method: "POST",
    body: JSON.stringify({
      name: repoName,
      project: repoName,
      target: "production",
      gitSource: { type: "github", org: GITHUB_ORG, repo: repoName, ref: "main" },
    }),
  }) as Promise<{ id: string; url: string; readyState: string }>;
}

export type DeploymentSnapshot = {
  id: string;
  url: string;
  readyState: string;
  alias?: string[];
};

/**
 * Makes exactly ONE Vercel API call to read a deployment's current
 * `readyState` — the single-check building block both the (now
 * request-scoped) `GET .../deploy-status` route and `waitForDeploymentReady`
 * are built on. Does no waiting/sleeping/looping of its own; callers decide
 * whether and how to retry.
 *
 * Propagates `VercelApiError` immediately on `ERROR`/`CANCELED` readyState
 * (these are terminal failures, not "not ready yet") or on any transport
 * failure. Any other readyState (`QUEUED`, `BUILDING`, `INITIALIZING`, etc.)
 * is returned as-is for the caller to interpret as "still in progress".
 */
export async function checkDeploymentStatus(deploymentId: string): Promise<DeploymentSnapshot> {
  const deployment = (await vercelRequest(`/v13/deployments/${deploymentId}`, {
    method: "GET",
  })) as DeploymentSnapshot;

  if (deployment.readyState === "ERROR" || deployment.readyState === "CANCELED") {
    throw new VercelApiError(`Deployment ended in state ${deployment.readyState}`, 502);
  }

  return deployment;
}

/**
 * Polls a deployment until `readyState` is `READY`, mirroring
 * `waitForRepoReady`'s loop shape. Resolves with the final deployment
 * payload (so the caller can read `.url` / `.alias` off it without an
 * extra request). Rejects with `DeploymentNotReadyError` on timeout, or
 * propagates `VercelApiError` immediately on `ERROR`/`CANCELED` states or
 * transport failures.
 *
 * NOT used by the live `POST .../generate-site` request path anymore — a
 * synchronous multi-minute poll inside a serverless function request is
 * unsafe (see module docs / `.pipeline/changes.md` for the platform-timeout
 * finding that motivated this). Kept exported for tests/tooling that still
 * want a "wait until done" helper outside the request/response cycle (e.g.
 * a future background job or CLI script), built on the same single-check
 * `checkDeploymentStatus` the live status-polling route uses.
 */
export async function waitForDeploymentReady(
  deploymentId: string,
  options?: { timeoutMs?: number; intervalMs?: number }
): Promise<DeploymentSnapshot> {
  const timeoutMs = options?.timeoutMs ?? 180_000;
  const intervalMs = options?.intervalMs ?? 3000;
  const deadline = Date.now() + timeoutMs;
  let lastState: string | undefined;

  while (true) {
    const deployment = await checkDeploymentStatus(deploymentId);

    lastState = deployment.readyState;
    if (deployment.readyState === "READY") return deployment;

    if (Date.now() >= deadline) {
      throw new DeploymentNotReadyError(deploymentId, lastState);
    }

    await new Promise((resolve) => setTimeout(resolve, intervalMs));
  }
}

/** Picks the clean production alias if Vercel assigned one, else the raw deployment URL. */
export function resolveLiveUrl(deployment: { url: string; alias?: string[] }): string {
  if (deployment.alias && deployment.alias.length > 0) {
    return `https://${deployment.alias[0]}`;
  }
  return `https://${deployment.url}`;
}
