import { buildClientData, slugify, TEMPLATE_MAP, type TemplateKey } from "template-shared";
import type { LeadRecord } from "@/lib/types";

export type SiteCategory = TemplateKey; // "landing" | "booking" | "payments"

export const SITE_CATEGORIES: readonly SiteCategory[] = ["landing", "booking", "payments"];

/**
 * Maps a LeadRecord into the `RawLeadJson` shape template-shared's
 * buildClientData() expects (mirrors demo-generator's client.json
 * "business" sub-object).
 */
export function leadToRawJson(lead: LeadRecord, category: SiteCategory) {
  return {
    business: {
      name: lead.businessName,
      category: lead.niche || "Local Business",
      phone: lead.phoneNumber || "",
      email: lead.email || "",
      address: lead.address || lead.city || "",
      website: lead.websiteUrl || "",
      photo: "",
      rating: lead.googleRating ?? undefined,
      reviewCount: undefined,
      openingHours: [],
      googleMapsUrl: lead.googleMapsLink || "",
    },
    meta: { template: category },
  };
}

/** Pure: lead + category -> { repoName, templateRepo, shape, clientData }. */
export function buildSiteGenerationPlan(lead: LeadRecord, category: SiteCategory) {
  const shape = category === "landing" ? "landing" : "booking";
  const templateRepo = TEMPLATE_MAP[category];
  const repoName = slugify(lead.businessName);
  const clientData = buildClientData(leadToRawJson(lead, category), { shape });
  return { repoName, templateRepo, shape, clientData };
}

/**
 * Pure: produces the exact client.js file body for landing-shape repos,
 * matching template-landing-page's `window.CLIENT_DATA = {...}` format.
 */
export function buildClientJsContent(clientData: unknown): string {
  return `// Generated by Agency-CRM lead-to-site connector\n// ${new Date().toISOString()}\nwindow.CLIENT_DATA = ${JSON.stringify(clientData, null, 2)};\n`;
}

const GITHUB_API = "https://api.github.com";
const GITHUB_ORG = "O-I-AI-soultions";

export class GitHubApiError extends Error {
  constructor(
    message: string,
    public status: number,
    /** True when the response carried GitHub's rate-limit-exhausted signal
     *  (429, or 403 with `X-RateLimit-Remaining: 0`) — lets callers
     *  distinguish rate-limiting from a generic 403 permission failure. */
    public rateLimited = false
  ) {
    super(message);
  }
}

/**
 * Thrown by `waitForRepoReady` when the polling timeout elapses without the
 * repo's template files (specifically client.json) becoming available.
 */
export class RepoNotReadyError extends Error {
  constructor(public repoFullName: string) {
    super(`Repo ${repoFullName} did not become ready before timeout`);
  }
}

async function githubRequest(path: string, init: RequestInit) {
  const token = process.env.GITHUB_API_TOKEN;
  if (!token) throw new GitHubApiError("Missing GITHUB_API_TOKEN", 500);

  const res = await fetch(`${GITHUB_API}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      ...(init.headers || {}),
    },
  });

  if (!res.ok) {
    const body = await res.json().catch(() => null);
    const rateLimited =
      res.status === 429 ||
      (res.status === 403 && res.headers.get("x-ratelimit-remaining") === "0");
    throw new GitHubApiError(
      body?.message || `GitHub API error (HTTP ${res.status})`,
      res.status,
      rateLimited
    );
  }
  return res.json();
}

/** Step 1: create repo from template. Returns the new repo's html_url + full_name. */
export async function createRepoFromTemplate(templateRepo: string, repoName: string) {
  return githubRequest(`/repos/${GITHUB_ORG}/${templateRepo}/generate`, {
    method: "POST",
    body: JSON.stringify({
      owner: GITHUB_ORG,
      name: repoName,
      private: true,
      include_all_branches: false,
    }),
  }) as Promise<{ html_url: string; full_name: string }>;
}

/**
 * Polls a newly-generated repo until its template files have actually
 * landed, using `GET /repos/{repoFullName}/contents/client.json` as the
 * readiness signal (see module docs above for the race this guards against).
 *
 * - 200 -> ready, resolves immediately (first check happens with no upfront
 *   sleep, so the already-ready case costs exactly one request).
 * - 404 (`GitHubApiError` with status 404) -> not ready yet, wait
 *   `intervalMs` and retry.
 * - Any other error propagates immediately (rate limit, 5xx, missing token,
 *   etc.) — it is not swallowed into the timeout.
 * - If `timeoutMs` elapses without a 200, rejects with `RepoNotReadyError`.
 */
export async function waitForRepoReady(
  repoFullName: string,
  options?: { timeoutMs?: number; intervalMs?: number }
): Promise<void> {
  const timeoutMs = options?.timeoutMs ?? 20000;
  const intervalMs = options?.intervalMs ?? 1500;
  const deadline = Date.now() + timeoutMs;

  while (true) {
    try {
      await githubRequest(`/repos/${repoFullName}/contents/client.json`, {
        method: "GET",
      });
      return;
    } catch (err) {
      if (!(err instanceof GitHubApiError) || err.status !== 404) throw err;
      // Not ready yet — fall through to the timeout/retry check below.
    }

    if (Date.now() >= deadline) {
      throw new RepoNotReadyError(repoFullName);
    }

    await new Promise((resolve) => setTimeout(resolve, intervalMs));
  }
}

/** Step 2: commit (create or update) a file's content via Contents API. */
export async function putRepoFile(
  repoFullName: string,
  filePath: string,
  content: string,
  message: string
) {
  // Must check for an existing file SHA first — PUT requires `sha` to
  // update an existing file, omitting it only works for file creation.
  // Template-generated repos already contain client.json/client.js with
  // placeholder content, so this is always an update, not a create.
  let sha: string | undefined;
  try {
    const existing = (await githubRequest(`/repos/${repoFullName}/contents/${filePath}`, {
      method: "GET",
    })) as { sha: string };
    sha = existing.sha;
  } catch (err) {
    if (!(err instanceof GitHubApiError) || err.status !== 404) throw err;
    // 404 is fine — file doesn't exist yet, sha stays undefined (create).
  }

  return githubRequest(`/repos/${repoFullName}/contents/${filePath}`, {
    method: "PUT",
    body: JSON.stringify({
      message,
      content: Buffer.from(content, "utf8").toString("base64"),
      ...(sha ? { sha } : {}),
    }),
  });
}
